# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface\Hoop.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titlebar = QtWidgets.QFrame(self.centralwidget)
        self.titlebar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titlebar.setStyleSheet("background-color: rgb(29, 27, 33);\n"
"color: rgb(30, 179, 137);\n"
"font: 10pt \"Segoe UI\";\n"
"border: 0px;")
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titlebar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(361, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.apptitle = QtWidgets.QLabel(self.titlebar)
        self.apptitle.setObjectName("apptitle")
        self.horizontalLayout_2.addWidget(self.apptitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.minimize = QtWidgets.QPushButton(self.titlebar)
        self.minimize.setMinimumSize(QtCore.QSize(10, 10))
        self.minimize.setMaximumSize(QtCore.QSize(10, 10))
        self.minimize.setBaseSize(QtCore.QSize(10, 10))
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("background-color: rgb(30, 179, 137);\n"
"border: 1px outset;\n"
"border-radius: 8px;\n"
"border-color:rgb(30, 179, 137);")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.maximize = QtWidgets.QPushButton(self.titlebar)
        self.maximize.setMaximumSize(QtCore.QSize(10, 10))
        self.maximize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximize.setStyleSheet("background-color: rgb(30, 179, 137);\n"
"border: 1px outset;\n"
"border-radius: 8px;\n"
"border-color:rgb(30, 179, 137);")
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_2.addWidget(self.maximize)
        self.exit = QtWidgets.QPushButton(self.titlebar)
        self.exit.setMaximumSize(QtCore.QSize(10, 10))
        self.exit.setBaseSize(QtCore.QSize(10, 10))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("background-color: rgb(30, 179, 137);\n"
"border: 1px outset;\n"
"border-radius: 8px;\n"
"border-color:rgb(30, 179, 137);")
        self.exit.setObjectName("exit")
        self.horizontalLayout_2.addWidget(self.exit)
        self.verticalLayout.addWidget(self.titlebar)
        self.menubar = QtWidgets.QFrame(self.centralwidget)
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.menubar.setStyleSheet("background-color: rgb(25, 23, 22);\n"
"color: rgb(30, 179, 137);\n"
"font: 10pt \"Segoe UI\";\n"
"border: 0px;")
        self.menubar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menubar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menubar.setObjectName("menubar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menubar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newfile = QtWidgets.QPushButton(self.menubar)
        self.newfile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.newfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newfile.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(255, 74, 98);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"")
        self.newfile.setObjectName("newfile")
        self.horizontalLayout.addWidget(self.newfile)
        self.openfile = QtWidgets.QPushButton(self.menubar)
        self.openfile.setMaximumSize(QtCore.QSize(16777215, 20))
        self.openfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openfile.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(255, 74, 98);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"")
        self.openfile.setObjectName("openfile")
        self.horizontalLayout.addWidget(self.openfile)
        self.savefile = QtWidgets.QPushButton(self.menubar)
        self.savefile.setMinimumSize(QtCore.QSize(0, 10))
        self.savefile.setMaximumSize(QtCore.QSize(16777215, 20))
        self.savefile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savefile.setStyleSheet("QPushButton:pressed{\n"
"    background-color: rgb(255, 74, 98);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"")
        self.savefile.setObjectName("savefile")
        self.horizontalLayout.addWidget(self.savefile)
        self.verticalLayout.addWidget(self.menubar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(25, 23, 22);\n"
"color: rgb(30, 179, 137);\n"
"font: 10pt \"Segoe UI\";\n"
"border: 0px;")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.texteditor = QtWidgets.QTextEdit(self.content)
        self.texteditor.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.texteditor.setObjectName("texteditor")
        self.verticalLayout_2.addWidget(self.texteditor)
        self.verticalLayout.addWidget(self.content)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 45)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apptitle.setText(_translate("MainWindow", "Hoop"))
        self.minimize.setText(_translate("MainWindow", "PushButton"))
        self.maximize.setText(_translate("MainWindow", "PushButton"))
        self.exit.setText(_translate("MainWindow", "PushButton"))
        self.newfile.setText(_translate("MainWindow", "New"))
        self.openfile.setText(_translate("MainWindow", "Open"))
        self.savefile.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
